apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: customer-microservice
  name: customer-microservice
  namespace: covertree
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-microservice
  strategy: {}
  template:
    metadata:
      labels:
        app: customer-microservice
    spec:
      containers:
      - image: IMAGE_NAME:IMAGE_TAG
        name: customer-microservice
        volumeMounts:
        - name: pubsub
          mountPath: /opt/pubsub/
          readOnly: true
      volumes:
      - name: pubsub
        secret:
          secretName: pubsub
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: customer-microservice
  name: customer-microservice-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4008
  selector:
    app: customer-microservice
  type: ClusterIP
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: devrootvik 
spec:
  domains:
    - dev.rootvik.net
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: external-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: frontend-static-ip
    networking.gke.io/managed-certificates: devrootvik
spec:
  rules:
  - host: dev.rootvik.net
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx-svc
          servicePort: 80
