apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: customer-microservice
  name: customer-microservice
  namespace: covertree
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-microservice
  strategy: {}
  template:
    metadata:
      labels:
        app: customer-microservice
    spec:
      containers:
      - image: IMAGE_NAME:IMAGE_TAG
        name: customer-microservice
        volumeMounts:
        - name: pubsub
          mountPath: /opt/pubsub/
          readOnly: true
      volumes:
      - name: pubsub
        secret:
          secretName: pubsub
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: customer-microservice
  name: customer-microservice-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4008
  selector:
    app: customer-microservice
  type: ClusterIP
